### PR TITLE
Add python page

### PR DESCRIPTION
**Pull request by CBElizabeth**
Here's my first pass at adding a python-specific sales page. 

Some notes:
* /python
* Copy still needs some wordsmithing, possibly a tagline to pair with "Python Craftsmen with startup experience."
* If we want to use this logo (or something like it) that is derived from the Python logo I'll reach out to psf-trademarks@python.org to make sure that it is acceptable.

### CODE REVIEW

**Comment by vaughncm** [comment]
Not sure if this is the right page but I assumed there'd be some concept of a partial template. Can we commonize some things? Feel free to bring me in the loop.

https://docs.djangoproject.com/en/1.9/ref/templates/language/#template-inheritance

**Comment by bcostlow** [comment]
Yeah, we're at many of once, twice, many on this. But I'd be inclined to accept this and do the refactor in another PR.

**Comment by bcostlow** [comment]
Also, based on the nominative use case rules, I don't think using the PSF logo is an issue. But our scenario isn't described *exactly* so go ahead and clear it—don't want to make enemies.

**Comment by CBElizabeth** [comment]
Definitely agree about splitting it into templates/partials. I did a little bit of digging into how to do that in Django (I was going to split out the team section as an experiment because it was bugging me), but my understanding of it made it seem exceedingly complicated. This is something I'd love to pair on when I'm not plague-ridden.

**Comment by vaughncm** [comment]
As it's not client-specific I agree that it should be put on the backburner if it's going to take a while however I'd like to at least timebox it to something reasonable (~1 hour) and see if we can't get it knocked out. Let's hit it when you're up to it.

**Comment by vaughncm** [comment]
Elizabeth and I commonized elements of the pages. Any other thoughts?

**Pull request merged**
